Defaulting the line number to UID rather than null
webdriverio-community/wdio-cucumberjs-json-reporter pull request #89
Opened 2022-03-01 11:03 UTC by manoj-fsbtech

2022-03-06 07:24 UTC, wswebcreation requested changes
Thanks for this PR and sorry for my late response. 

Can you check the comment and also make sure that this is covered in a unit test?

Thanks!

2022-03-06 07:24 UTC, wswebcreation commented on lib/reporter.ts
> +        log.info( '&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&' );
Can you remove the logs?

2022-03-08 07:05 UTC, wswebcreation commented
@manoj-fsbtech 

Can you also check the unit tests, they are breaking now

2022-08-22 14:24 UTC, Nemesischild commented
Is there any update on when this branch will be merged & made available for general use. This null line issue is blocking me on the next phase of my automation & CI/CD integration

2023-02-28 17:56 UTC, christian-bromann commented
@Nemesischild mind raising a new PR so we can move forward with this?

2023-04-28 19:07 UTC, christian-bromann commented
Closing due to inactivity. Please re-raise the PR if there is still interest.

2023-04-28 19:07 UTC, closed without merging